targets:
  $default:
    builders:
      freezed:
        options:
          fallback_union: default
        generate_for:
          include:
            - "lib/src/features/**/application/**.dart"
            - "lib/src/features/**/domain/**.dart"

      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - "lib/src/features/**/domain/**.dart"

      riverpod_generator:
        generate_for:
          include:
            - "lib/src/features/**/application/**.dart"
            - "lib/src/features/**/data/**.dart"
            - "lib/src/routing/**.dart"
            - "lib/*.dart"

      go_router_builder:
        generate_for:
          include:
            - "lib/src/features/**/presentation/**.dart"
            - "lib/src/routing/**.dart"

      lm_labs_generator|routes:
        generate_for:
          include:
            - "lib/src/features/*/presentation/**_routes.dart"
